## Append samples of your project ##
resources:
- myetcd_v1_operator.yaml
- myetcd_v1_restore.yaml
- myetcd_v1_backup.yaml
- myetcd_v1_etcdcluster.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
