apiVersion: myetcd.aaron.io/v1
kind: Restore
metadata:
  labels:
    app.kubernetes.io/name: restore
    app.kubernetes.io/instance: restore-sample
    app.kubernetes.io/part-of: myetcd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: myetcd-operator
  name: restore-sample
spec:
  # TODO(user): Add fields here
